curl 'http://localhost:8090/api/projects' \
  -H 'Connection: keep-alive' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.67 Safari/537.36' \
  -H 'content-type: application/json' \
  -H 'Accept: */*' \
  -H 'Origin: http://localhost:4200' \
  -H 'Sec-Fetch-Site: same-site' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Referer: http://localhost:4200/' \
  -H 'Accept-Language: en,ro-RO;q=0.9,ro;q=0.8,en-US;q=0.7,de;q=0.6,fr;q=0.5' \
  -H 'Cookie: connect.sid=s%3ASIKl7Pn5Nz-c5wq9UQIXaD1LFc_Yjoy7.zyGmjm5LinNNT720DW4RYUs7t%2FazzKHi4T9Vd0h3iQA; io=dyTAWyDArKaFEadqAAAG' \
  --data-binary '{"name":"hermes-node-sample-app-s3","stages":[{"type":"aws","name":"spec-fe","band":"qa","regions":["eu-west-1"],"resourceName":"aluca-test-s3","resourceType":"s3"}]}' \
  --compressed